codecov:
  require_ci_to_pass: yes

coverage:
  range: 60..90
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        flags:
          - server
    patch:
      default:
        target: 85%
        threshold: 0%
        only_pulls: true
        if_ci_failed: ignore
        flags:
          - server

comment:
  layout: "diff, flags"
  require_changes: true
  show_critical_paths: true

flags:
  server:
    paths:
      - "**/*.py"
    carryforward: true
  ui-tests:
    paths:
      - "**/*.js"
    carryforward: true
  server-ui:
    paths:
      - "**/*.py"
    carryforward: true

profiling:
  critical_files_paths:
    - /nxenv/api.py
    - /nxenv/app.py
    - /nxenv/auth.py
    - /nxenv/boot.py
    - /nxenv/client.py
    - /nxenv/handler.py
    - /nxenv/migrate.py
    - /nxenv/sessions.py
    - /nxenv/utils/*
    - /nxenv/desk/reportview.py
    - /nxenv/desk/form/*
    - /nxenv/model/*
    - /nxenv/core/doctype/doctype/*
    - /nxenv/core/doctype/data_import/*
    - /nxenv/core/doctype/user/*
    - /nxenv/core/doctype/user/*
    - /nxenv/query_builder/*
    - /nxenv/database/*
